export const REQUEST = 'REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const GET_USER = 'GET_USER';
export const NO_ACTIVE_USER = 'NO_ACTIVE_USER';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const NO_CHANGE_IN_ACCOUNT = 'NO_CHANGE_IN_ACCOUNT';

export const REQUEST_OWNED_GAMES = 'REQUEST_OWNED_GAMES';
export const GET_OWNED_GAMES_SUCCESS = 'GET_OWNED_GAMES_SUCCESS';
export const GET_OWNED_GAMES_FAILED = 'GET_OWNED_GAMES_FAILED';

export const EMPTY_LIBRARY = 'EMPTY_LIBRARY';
export const LOGOUT = 'LOGOUT';

export const REQUEST_REDEEM_KEY = 'REQUEST_REDEEM_KEY';
export const REDEEM_KEY_SUCCESS = 'REDEEM_KEY_SUCCESS';
export const REDEEM_KEY_FAILED = 'REDEEM_KEY_FAILED';
export const REQUEST_REDEEMED_GAME = 'REQUEST_REDEEMED_GAME';
export const GET_REDEEMED_GAME = 'GET_REDEEMED_GAME';
export const USER_IS_NOTIFIED = 'USER_IS_NOTIFIED';

export const REQUEST_ALL_USERS = 'REQUEST_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const ADMIN_REQUEST = 'ADMIN_REQUEST';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAILED = 'ADMIN_UPDATE_USER_FAILED';
export const CLEAR_USERS = 'CLEAR_USERS';
export const ADMIN_GET_USER_GAMES_SUCCESS = 'ADMIN_GET_USER_GAMES_SUCCESS';
export const ADMIN_GET_USER_GAMES_FAILED = 'ADMIN_GET_USER_GAMES_FAILED';
export const ADMIN_REVOKE_OWNERSHIP_SUCCESS = 'ADMIN_REVOKE_OWNERSHIP_SUCCESS';
export const ADMIN_REVOKE_OWNERSHIP_FAILED = 'ADMIN_REVOKE_OWNERSHIP_FAILED';
export const ADMIN_GRANT_OWNERSHIP_SUCCESS = 'ADMIN_GRANT_OWNERSHIP_SUCCESS';
export const ADMIN_GRANT_OWNERSHIP_FAILED = 'ADMIN_GRANT_OWNERSHIP_FAILED';

export const REQUEST_ALL_GAMES = 'REQUEST_ALL_GAMES';
export const ADMIN_GET_ALL_GAMES_SUCCESS = 'ADMIN_GET_ALL_GAMES_SUCCESS';
export const ADMIN_GET_ALL_GAMES_FAILED = 'ADMIN_GET_ALL_GAMES_FAILED';
export const CLEAR_OWNERSHIP = 'CLEAR_OWNERSHIP';
